In [1]:
# 02_flight_model_training.ipynb

from pathlib import Path
import mlflow

# Make sure project root is on sys.path
import sys, os
PROJECT_ROOT = Path.cwd().parent  # notebooks/ → project root
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)

from src.data_handler import load_csv
from src.data_wrangling import wrangle_flights
from src.data_preprocessing import preprocess_flights, data_spliting
from src.training import train_flight_price_model
from src.prediction import predict_flight_price

PROJECT_ROOT: C:\Users\srush\Desktop\00_Labmentix\14_Voyage_ML\Voyage_Analytics

In [2]:
RAW_DIR = PROJECT_ROOT / "data" / "raw"

flights = load_csv(RAW_DIR / "flights.csv")
print("Flights wrangled shape:", flights.shape)
display(flights.head())

Flights wrangled shape: (271888, 10)

,travelCode,userCode,from,to,flightType,price,time,distance,agency,date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,09/26/2019
1,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,09/30/2019
2,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,10/03/2019
3,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,10/04/2019
4,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019

In [4]:
# Data Wrangling
flights_wrangled = wrangle_flights(flights)
print("Flights_wrangled shape:", flights_wrangled.shape)
display(flights_wrangled.head())

Flights_wrangled shape: (271888, 10)

,travelcode,usercode,from,to,flighttype,price,time,distance,agency,date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,2019-09-26
1,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,2019-09-30
2,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,2019-10-03
3,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,2019-10-04
4,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,2019-10-10

In [14]:
# Full preprocessing + feature engineering
flights_prep = preprocess_flights(flights_wrangled)
print("Flights_prep shape:", flights_prep.shape)
display(flights_prep.head())

# Build feature matrix and target
X_flight, y_flight = data_spliting(flights_prep, target_col = "price", drop_cols = ["travelcode", "usercode", "flighttype", "time", "distance", "date", "priceperkm"])
                                                                                    
print("X_flight shape:", X_flight.shape)
print("y_flight shape:", y_flight.shape)

Flights_prep shape: (271888, 112)

,travelcode,usercode,flighttype,price,time,distance,date,month,weekday,isweekend,...,route_Sao Paulo (SP)_Brasilia (DF),route_Sao Paulo (SP)_Campo Grande (MS),route_Sao Paulo (SP)_Florianopolis (SC),route_Sao Paulo (SP)_Natal (RN),route_Sao Paulo (SP)_Recife (PE),route_Sao Paulo (SP)_Rio de Janeiro (RJ),route_Sao Paulo (SP)_Salvador (BH),time_sc,distance_sc,priceperkm_sc
0,0,0,firstClass,1434.38,1.76,676.53,2019-09-26,9,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.624567,0.620416,0.320142
1,0,0,firstClass,1292.29,1.76,676.53,2019-09-30,9,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.624567,0.620416,0.017602
2,1,0,firstClass,1487.52,1.66,637.56,2019-10-03,10,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.440249,0.433824,0.626579
3,1,0,firstClass,1127.36,1.66,637.56,2019-10-04,10,4,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.440249,0.433824,-0.187079
4,2,0,firstClass,1684.05,2.16,830.86,2019-10-10,10,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.361841,1.359364,0.186509

X_flight shape: (271888, 104)
y_flight shape: (271888,)