In [1]:
# 02_flight_model_training.ipynb

from pathlib import Path
import mlflow

# Make sure project root is on sys.path
import sys, os
PROJECT_ROOT = Path.cwd().parent  # notebooks/ → project root
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)

from src.data_handler import load_csv
from src.data_wrangling import wrangle_flights
from src.data_preprocessing import preprocess_flights, data_spliting_Xy, data_spliting_X
from src.training import train_flight_price_model
from src.prediction import predict_flight_price

PROJECT_ROOT: C:\Users\srush\Desktop\00_Labmentix\14_Voyage_ML\Voyage_Analytics

In [2]:
RAW_DIR = PROJECT_ROOT / "data" / "raw"

flights = load_csv(RAW_DIR / "flights.csv")
print("Flights wrangled shape:", flights.shape)
display(flights.head())

Flights wrangled shape: (271888, 10)

,travelCode,userCode,from,to,flightType,price,time,distance,agency,date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,09/26/2019
1,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,09/30/2019
2,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,10/03/2019
3,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,10/04/2019
4,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,10/10/2019

In [3]:
# Data Wrangling
flights_wrangled = wrangle_flights(flights)
print("Flights_wrangled shape:", flights_wrangled.shape)
display(flights_wrangled.head())

Flights_wrangled shape: (271888, 10)

,travelcode,usercode,from,to,flighttype,price,time,distance,agency,date
0,0,0,Recife (PE),Florianopolis (SC),firstClass,1434.38,1.76,676.53,FlyingDrops,2019-09-26
1,0,0,Florianopolis (SC),Recife (PE),firstClass,1292.29,1.76,676.53,FlyingDrops,2019-09-30
2,1,0,Brasilia (DF),Florianopolis (SC),firstClass,1487.52,1.66,637.56,CloudFy,2019-10-03
3,1,0,Florianopolis (SC),Brasilia (DF),firstClass,1127.36,1.66,637.56,CloudFy,2019-10-04
4,2,0,Aracaju (SE),Salvador (BH),firstClass,1684.05,2.16,830.86,CloudFy,2019-10-10

In [4]:
# Full preprocessing + feature engineering
flights_prep = preprocess_flights(flights_wrangled)
print("Flights_prep shape:", flights_prep.shape)
display(flights_prep.head())

# Build feature matrix and target
X_flight, y_flight = data_spliting_Xy(flights_prep, target_col = "price", drop_cols = ["travelcode", "usercode", "flighttype", "time", "distance", "date"])
                                                                                    
print("X_flight shape:", X_flight.shape)
print("y_flight shape:", y_flight.shape)
display(X_flight.head())
display(y_flight.head())

Flights_prep shape: (271888, 110)

,travelcode,usercode,flighttype,price,time,distance,date,month,weekday,isweekend,...,route_Sao Paulo (SP)_Aracaju (SE),route_Sao Paulo (SP)_Brasilia (DF),route_Sao Paulo (SP)_Campo Grande (MS),route_Sao Paulo (SP)_Florianopolis (SC),route_Sao Paulo (SP)_Natal (RN),route_Sao Paulo (SP)_Recife (PE),route_Sao Paulo (SP)_Rio de Janeiro (RJ),route_Sao Paulo (SP)_Salvador (BH),time_sc,distance_sc
0,0,0,firstClass,1434.38,1.76,676.53,2019-09-26,9,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.624567,0.620416
1,0,0,firstClass,1292.29,1.76,676.53,2019-09-30,9,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.624567,0.620416
2,1,0,firstClass,1487.52,1.66,637.56,2019-10-03,10,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.440249,0.433824
3,1,0,firstClass,1127.36,1.66,637.56,2019-10-04,10,4,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.440249,0.433824
4,2,0,firstClass,1684.05,2.16,830.86,2019-10-10,10,3,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.361841,1.359364

X_flight shape: (271888, 103)
y_flight shape: (271888,)

,month,weekday,isweekend,quarter,flighttype_enc,from_Aracaju (SE),from_Brasilia (DF),from_Campo Grande (MS),from_Florianopolis (SC),from_Natal (RN),...,route_Sao Paulo (SP)_Aracaju (SE),route_Sao Paulo (SP)_Brasilia (DF),route_Sao Paulo (SP)_Campo Grande (MS),route_Sao Paulo (SP)_Florianopolis (SC),route_Sao Paulo (SP)_Natal (RN),route_Sao Paulo (SP)_Recife (PE),route_Sao Paulo (SP)_Rio de Janeiro (RJ),route_Sao Paulo (SP)_Salvador (BH),time_sc,distance_sc
0,9,3,0,3,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.624567,0.620416
1,9,0,0,3,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.624567,0.620416
2,10,3,0,4,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.440249,0.433824
3,10,4,0,4,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.440249,0.433824
4,10,3,0,4,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.361841,1.359364

0    1434.38
1    1292.29
2    1487.52
3    1127.36
4    1684.05
Name: price, dtype: float64

In [5]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")  # adjust if needed

results = train_flight_price_model(experiment_name = "voyage_flight_price")

best_model_name = results["best_model"]
print("\nBest model:", best_model_name)
print("Best test RMSE:", results["results"][best_model_name]["test_rmse"])
print("Best test R² :", results["results"][best_model_name]["test_r2"])

Loading raw data...
Flight rows loaded: 271888
Wrangling...
Preprocessing...
Feature matrix shape: (271888, 103), Target shape: (271888,)
Features saved

2026/01/12 23:36:03 INFO mlflow.tracking.fluent: Experiment with name 'voyage_flight_price' does not exist. Creating a new experiment.

Train: (217510, 103), Test: (54378, 103)

Training ridge...

2026/01/12 23:36:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/01/12 23:36:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Saved model to: C:\Users\srush\Desktop\00_Labmentix\14_Voyage_ML\Voyage_Analytics\models\ridge_flight.pkl
🏃 View run flight_ridge at: http://127.0.0.1:5000/#/experiments/698140844866323914/runs/356928f1ae464417b4d3f006983d8e94
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/698140844866323914

Training random_forest...

2026/01/12 23:37:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/01/12 23:37:39 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Saved model to: C:\Users\srush\Desktop\00_Labmentix\14_Voyage_ML\Voyage_Analytics\models\random_forest_flight.pkl
🏃 View run flight_random_forest at: http://127.0.0.1:5000/#/experiments/698140844866323914/runs/616d8b1bd21246ba984c6751bb7fa8a8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/698140844866323914

Training gradient_boosting...

2026/01/12 23:39:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/01/12 23:39:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Saved model to: C:\Users\srush\Desktop\00_Labmentix\14_Voyage_ML\Voyage_Analytics\models\gradient_boosting_flight.pkl
🏃 View run flight_gradient_boosting at: http://127.0.0.1:5000/#/experiments/698140844866323914/runs/d4e3857bb5ae4dcbbba2d9cad09bea80
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/698140844866323914

Best model: random_forest
Test RMSE: 9.70
Test R²: 0.999

Best model: random_forest
Best test RMSE: 9.702188556998907
Best test R² : 0.9992840531070138

In [6]:
for name, res in results["results"].items():
    print(f"\nModel: {name}")
    print(f"  Train RMSE: {res['train_rmse']:.2f}")
    print(f"  Test  RMSE: {res['test_rmse']:.2f}")
    print(f"  Train R² : {res['train_r2']:.3f}")
    print(f"  Test  R² : {res['test_r2']:.3f}")

Model: ridge
  Train RMSE: 184.42
  Test  RMSE: 184.69
  Train R² : 0.740
  Test  R² : 0.741

Model: random_forest
  Train RMSE: 9.73
  Test  RMSE: 9.70
  Train R² : 0.999
  Test  R² : 0.999

Model: gradient_boosting
  Train RMSE: 19.87
  Test  RMSE: 19.85
  Train R² : 0.997
  Test  R² : 0.997

In [7]:
# Choose the best model file
model_path = PROJECT_ROOT / "models" / f"{best_model_name}_flight.pkl"
print("Using model:", model_path)

sample_input = {
    "from": flights["from"].iloc[0],
    "to": flights["to"].iloc[0],
    "flighttype": flights["flightType"].iloc[0],
    "agency": flights["agency"].iloc[0],
    "distance": float(flights["distance"].iloc[0]),
    "time": float(flights["time"].iloc[0]),
    "date": str(flights["date"].iloc[0]) if "date" in flights.columns else "2026-01-15",
}

prediction_result = predict_flight_price(
    model_path=model_path,
    input_data=sample_input,
)

prediction_result

Using model: C:\Users\srush\Desktop\00_Labmentix\14_Voyage_ML\Voyage_Analytics\models\random_forest_flight.pkl
Model loaded
Sample input loaded
Sample input wrangled
Sample input preprocessed
['flighttype', 'distance', 'time', 'date', 'month', 'weekday', 'isweekend', 'quarter', 'flighttype_enc', 'from_Recife (PE)', 'to_Florianopolis (SC)', 'agency_FlyingDrops', 'season_fall', 'route_Recife (PE)_Florianopolis (SC)', 'time_sc', 'distance_sc']
   month  weekday  isweekend  quarter  flighttype_enc  from_Aracaju (SE)  \
0      9        3          0        3             1.0                  0

   from_Brasilia (DF)  from_Campo Grande (MS)  from_Florianopolis (SC)  \
0                   0                       0                        0

   from_Natal (RN)  ...  route_Sao Paulo (SP)_Aracaju (SE)  \
0                0  ...                                  0

   route_Sao Paulo (SP)_Brasilia (DF)  route_Sao Paulo (SP)_Campo Grande (MS)  \
0                                   0                                       0

   route_Sao Paulo (SP)_Florianopolis (SC)  route_Sao Paulo (SP)_Natal (RN)  \
0                                        0                                0

   route_Sao Paulo (SP)_Recife (PE)  route_Sao Paulo (SP)_Rio de Janeiro (RJ)  \
0                                 0                                         0

   route_Sao Paulo (SP)_Salvador (BH)  time_sc  distance_sc
0                                   0      0.0          0.0

[1 rows x 103 columns]

{'predicted_price': 1379.7394000000068,
 'confidence': 0.95,
 'price_range': [np.float64(1241.7654600000062),
  np.float64(1517.7133400000075)]}